export const API_ENDPOINTS = {
  auth: {
    login: "/api/v1/auth/login",
    register: "/api/v1/auth/register",
    logout: "/api/v1/auth/logout",
    refresh: "/api/v1/auth/refresh",
    me: "/api/v1/auth/me",
  },
  clients: {
    list: "/api/v1/clients",
    stats: "/api/v1/clients/stats",
    create: "/api/v1/clients",
    detail: (id: string) => `/api/v1/clients/${id}`,
    update: (id: string) => `/api/v1/clients/${id}`,
    delete: (id: string) => `/api/v1/clients/${id}`,
    contacts: (id: string) => `/api/v1/clients/${id}/contacts`,
    addContact: (id: string) => `/api/v1/clients/${id}/contacts`,
    updateContact: (clientId: string, contactId: string) => `/api/v1/clients/${clientId}/contacts/${contactId}`,
    removeContact: (clientId: string, contactId: string) => `/api/v1/clients/${clientId}/contacts/${contactId}`,
    activities: (id: string) => `/api/v1/clients/${id}/activities`,
  },
  legal: {
    list: "/api/v1/legal",
    stats: "/api/v1/legal/stats",
    create: "/api/v1/legal",
    detail: (id: string) => `/api/v1/legal/${id}`,
    update: (id: string) => `/api/v1/legal/${id}`,
    delete: (id: string) => `/api/v1/legal/${id}`,
    uploadVersion: (id: string) => `/api/v1/legal/${id}/versions`,
    versions: (id: string) => `/api/v1/legal/${id}/versions`,
    activities: (id: string) => `/api/v1/legal/${id}/activities`,
  },
  finance: {
    stats: "/api/v1/finance/stats",
    overdue: "/api/v1/finance/overdue",
    records: "/api/v1/finance/records",
    recordDetail: (id: string) => `/api/v1/finance/records/${id}`,
    invoices: "/api/v1/finance/invoices",
    invoiceDetail: (id: string) => `/api/v1/finance/invoices/${id}`,
    payments: "/api/v1/finance/payments",
    paymentDetail: (id: string) => `/api/v1/finance/payments/${id}`,
    clientSummary: (clientId: string) => `/api/v1/finance/clients/${clientId}/summary`,
    activities: "/api/v1/finance/activities",
  },
  leads: {
    list: "/api/v1/leads",
    stats: "/api/v1/leads/stats",
    create: "/api/v1/leads",
    detail: (id: string) => `/api/v1/leads/${id}`,
    update: (id: string) => `/api/v1/leads/${id}`,
    delete: (id: string) => `/api/v1/leads/${id}`,
    updateStatus: (id: string) => `/api/v1/leads/${id}/status`,
    convert: (id: string) => `/api/v1/leads/${id}/convert`,
    activities: (leadId: string) => `/api/v1/leads/${leadId}/activities`,
    meetings: (leadId: string) => `/api/v1/leads/${leadId}/meetings`,
    updateMeeting: (leadId: string, meetingId: string) => `/api/v1/leads/${leadId}/meetings/${meetingId}`,
    deleteMeeting: (leadId: string, meetingId: string) => `/api/v1/leads/${leadId}/meetings/${meetingId}`,
    actionItems: (leadId: string, meetingId: string) => `/api/v1/leads/${leadId}/meetings/${meetingId}/action-items`,
    updateActionItem: (leadId: string, meetingId: string, itemIndex: number) => `/api/v1/leads/${leadId}/meetings/${meetingId}/action-items/${itemIndex}`,
  },
  roles: {
    list: "/api/v1/roles",
    create: "/api/v1/roles",
    detail: (id: string) => `/api/v1/roles/${id}`,
    update: (id: string) => `/api/v1/roles/${id}`,
    delete: (id: string) => `/api/v1/roles/${id}`,
  },
  agreements: {
    list: "/api/v1/agreements",
    create: "/api/v1/agreements",
    detail: (id: string) => `/api/v1/agreements/${id}`,
    update: (id: string) => `/api/v1/agreements/${id}`,
    delete: (id: string) => `/api/v1/agreements/${id}`,
    send: (id: string) => `/api/v1/agreements/${id}/send`,
    signInternal: (id: string) => `/api/v1/agreements/${id}/sign-internal`,
    setPassword: (id: string) => `/api/v1/agreements/${id}/set-password`,
    signatureStatus: (id: string) => `/api/v1/agreements/${id}/signature-status`,
    auditEvents: (id: string) => `/api/v1/agreements/${id}/audit-events`,
    evidencePackage: (id: string) => `/api/v1/agreements/${id}/evidence-package`,
    share: (token: string) => `/api/v1/agreements/share/${token}`,
    verifyPassword: (token: string) => `/api/v1/agreements/share/${token}/verify`,
    startSession: (token: string) => `/api/v1/agreements/share/${token}/session`,
    consent: (token: string) => `/api/v1/agreements/share/${token}/consent`,
    sign: (token: string) => `/api/v1/agreements/share/${token}/sign`,
  },
  branding: {
    get: "/api/v1/branding",
    update: "/api/v1/branding",
    uploadLogo: "/api/v1/branding/logo",
  },
  proposals: {
    generate: "/api/v1/proposals/generate",
    list: "/api/v1/proposals/proposals",
    detail: (id: string) => `/api/v1/proposals/proposals/${id}`,
    delete: (id: string) => `/api/v1/proposals/proposals/${id}`,
    updateContent: (id: string) => `/api/v1/proposals/proposals/${id}/content`,
    updateMetadata: (id: string) => `/api/v1/proposals/proposals/${id}/metadata`,
    publish: (id: string) => `/api/v1/proposals/proposals/${id}/publish`,
    versions: (id: string) => `/api/v1/proposals/proposals/${id}/versions`,
    versionDetail: (id: string, vid: string) => `/api/v1/proposals/proposals/${id}/versions/${vid}`,
    restoreVersion: (id: string, vid: string) => `/api/v1/proposals/proposals/${id}/versions/${vid}/restore`,
    setPassword: (id: string) => `/api/v1/proposals/proposals/${id}/set-password`,
    share: (token: string) => `/api/v1/proposals/proposals/share/${token}`,
    verifyPassword: (token: string) => `/api/v1/proposals/proposals/share/${token}/verify`,
    comments: (token: string) => `/api/v1/proposals/proposals/share/${token}/comments`,
    deleteComment: (token: string, commentId: string) => `/api/v1/proposals/proposals/share/${token}/comments/${commentId}`,
    toggleCommentStatus: (token: string, commentId: string) => `/api/v1/proposals/proposals/share/${token}/comments/${commentId}/status`,
    jobs: "/api/v1/proposals/jobs",
    jobDetail: (id: string) => `/api/v1/proposals/jobs/${id}`,
    stream: (jobId: string) => `/api/v1/proposals/jobs/${jobId}/stream`,
  },
  brd: {
    generate: "/api/v1/brd/generate",
    list: "/api/v1/brd/brds",
    detail: (id: string) => `/api/v1/brd/brds/${id}`,
    delete: (id: string) => `/api/v1/brd/brds/${id}`,
    updateContent: (id: string) => `/api/v1/brd/brds/${id}/content`,
    updateMetadata: (id: string) => `/api/v1/brd/brds/${id}/metadata`,
    publish: (id: string) => `/api/v1/brd/brds/${id}/publish`,
    versions: (id: string) => `/api/v1/brd/brds/${id}/versions`,
    versionDetail: (id: string, vid: string) => `/api/v1/brd/brds/${id}/versions/${vid}`,
    restoreVersion: (id: string, vid: string) => `/api/v1/brd/brds/${id}/versions/${vid}/restore`,
    setPassword: (id: string) => `/api/v1/brd/brds/${id}/set-password`,
    share: (token: string) => `/api/v1/brd/brds/share/${token}`,
    verifyPassword: (token: string) => `/api/v1/brd/brds/share/${token}/verify`,
    comments: (token: string) => `/api/v1/brd/brds/share/${token}/comments`,
    deleteComment: (token: string, commentId: string) => `/api/v1/brd/brds/share/${token}/comments/${commentId}`,
    toggleCommentStatus: (token: string, commentId: string) => `/api/v1/brd/brds/share/${token}/comments/${commentId}/status`,
    jobs: "/api/v1/brd/jobs",
    jobDetail: (id: string) => `/api/v1/brd/jobs/${id}`,
    stream: (jobId: string) => `/api/v1/brd/jobs/${jobId}/stream`,
  },
  sow: {
    generate: "/api/v1/sow/generate",
    list: "/api/v1/sow",
    detail: (id: string) => `/api/v1/sow/${id}`,
    delete: (id: string) => `/api/v1/sow/${id}`,
    features: (sowId: string) => `/api/v1/sow/${sowId}/features`,
    featureDetail: (featureId: string) => `/api/v1/sow/features/${featureId}`,
    featureUpdate: (featureId: string) => `/api/v1/sow/features/${featureId}`,
    featureSetPassword: (featureId: string) => `/api/v1/sow/features/${featureId}/set-password`,
    featureShare: (token: string) => `/api/v1/sow/features/share/${token}`,
    featureVerifyPassword: (token: string) => `/api/v1/sow/features/share/${token}/verify`,
    featureComments: (token: string) => `/api/v1/sow/features/share/${token}/comments`,
    featureCommentStatus: (token: string, commentId: string) => `/api/v1/sow/features/share/${token}/comments/${commentId}/status`,
    featureCommentDelete: (token: string, commentId: string) => `/api/v1/sow/features/share/${token}/comments/${commentId}`,
    setPassword: (id: string) => `/api/v1/sow/${id}/set-password`,
    jobDetail: (id: string) => `/api/v1/sow/jobs/${id}`,
    stream: (jobId: string) => `/api/v1/sow/jobs/${jobId}/stream`,
  },
  meetings: {
    list: "/api/v1/meetings",
    stats: "/api/v1/meetings/stats",
    create: "/api/v1/meetings",
    detail: (id: string) => `/api/v1/meetings/${id}`,
    update: (id: string) => `/api/v1/meetings/${id}`,
    delete: (id: string) => `/api/v1/meetings/${id}`,
    decisions: (id: string) => `/api/v1/meetings/${id}/decisions`,
    addDecision: (id: string) => `/api/v1/meetings/${id}/decisions`,
    updateDecision: (meetingId: string, decisionId: string) => `/api/v1/meetings/${meetingId}/decisions/${decisionId}`,
    deleteDecision: (meetingId: string, decisionId: string) => `/api/v1/meetings/${meetingId}/decisions/${decisionId}`,
    actionItems: (id: string) => `/api/v1/meetings/${id}/action-items`,
    addActionItem: (id: string) => `/api/v1/meetings/${id}/action-items`,
    updateActionItem: (meetingId: string, itemId: string) => `/api/v1/meetings/${meetingId}/action-items/${itemId}`,
    deleteActionItem: (meetingId: string, itemId: string) => `/api/v1/meetings/${meetingId}/action-items/${itemId}`,
    activities: (id: string) => `/api/v1/meetings/${id}/activities`,
    generateSummary: (id: string) => `/api/v1/meetings/${id}/generate-summary`,
    summaryJobStream: (jobId: string) => `/api/v1/meetings/summary-jobs/${jobId}/stream`,
    googleAuth: "/api/v1/meetings/auth/google",
    googleStatus: "/api/v1/meetings/auth/google/status",
    googleDisconnect: "/api/v1/meetings/auth/google/disconnect",
  },
  knowledge: {
    stats: "/api/v1/knowledge/stats",
    list: "/api/v1/knowledge",
    create: "/api/v1/knowledge",
    detail: (id: string) => `/api/v1/knowledge/${id}`,
    update: (id: string) => `/api/v1/knowledge/${id}`,
    delete: (id: string) => `/api/v1/knowledge/${id}`,
    restore: (id: string) => `/api/v1/knowledge/${id}/restore`,
    favorite: (id: string) => `/api/v1/knowledge/${id}/favorite`,
    favorites: "/api/v1/knowledge/favorites",
    versions: (id: string) => `/api/v1/knowledge/${id}/versions`,
    restoreVersion: (id: string, v: number) => `/api/v1/knowledge/${id}/versions/${v}/restore`,
    activities: (id: string) => `/api/v1/knowledge/${id}/activities`,
    related: (id: string) => `/api/v1/knowledge/${id}/related`,
  },

} as const;
