export const API_ENDPOINTS = {
  auth: {
    login: "/api/v1/auth/login",
    register: "/api/v1/auth/register",
    logout: "/api/v1/auth/logout",
    refresh: "/api/v1/auth/refresh",
    me: "/api/v1/auth/me",
  },
  documents: {
    list: "/api/v1/documents",
    stats: "/api/v1/documents/stats",
    upload: "/api/v1/documents",
    detail: (id: string) => `/api/v1/documents/${id}`,
    update: (id: string) => `/api/v1/documents/${id}`,
    delete: (id: string) => `/api/v1/documents/${id}`,
    replaceFile: (id: string) => `/api/v1/documents/${id}/replace`,
    activities: (id: string) => `/api/v1/documents/${id}/activities`,
  },
  meetings: {
    list: "/api/v1/meetings",
    stats: "/api/v1/meetings/stats",
    create: "/api/v1/meetings",
    detail: (id: string) => `/api/v1/meetings/${id}`,
    update: (id: string) => `/api/v1/meetings/${id}`,
    delete: (id: string) => `/api/v1/meetings/${id}`,
    decisions: (id: string) => `/api/v1/meetings/${id}/decisions`,
    addDecision: (id: string) => `/api/v1/meetings/${id}/decisions`,
    removeDecision: (mid: string, did: string) => `/api/v1/meetings/${mid}/decisions/${did}`,
    actionItems: (id: string) => `/api/v1/meetings/${id}/action-items`,
    createActionItem: (id: string) => `/api/v1/meetings/${id}/action-items`,
    updateActionItem: (mid: string, aid: string) => `/api/v1/meetings/${mid}/action-items/${aid}`,
    deleteActionItem: (mid: string, aid: string) => `/api/v1/meetings/${mid}/action-items/${aid}`,
    activities: (id: string) => `/api/v1/meetings/${id}/activities`,
  },
  clients: {
    list: "/api/v1/clients",
    stats: "/api/v1/clients/stats",
    create: "/api/v1/clients",
    detail: (id: string) => `/api/v1/clients/${id}`,
    update: (id: string) => `/api/v1/clients/${id}`,
    delete: (id: string) => `/api/v1/clients/${id}`,
    contacts: (id: string) => `/api/v1/clients/${id}/contacts`,
    addContact: (id: string) => `/api/v1/clients/${id}/contacts`,
    updateContact: (clientId: string, contactId: string) => `/api/v1/clients/${clientId}/contacts/${contactId}`,
    removeContact: (clientId: string, contactId: string) => `/api/v1/clients/${clientId}/contacts/${contactId}`,
    activities: (id: string) => `/api/v1/clients/${id}/activities`,
  },
  proposals: {
    list: "/api/v1/proposals",
    stats: "/api/v1/proposals/stats",
    create: "/api/v1/proposals",
    detail: (id: string) => `/api/v1/proposals/${id}`,
    update: (id: string) => `/api/v1/proposals/${id}`,
    delete: (id: string) => `/api/v1/proposals/${id}`,
    versions: (id: string) => `/api/v1/proposals/${id}/versions`,
    version: (id: string, vid: string) => `/api/v1/proposals/${id}/versions/${vid}`,
    activities: (id: string) => `/api/v1/proposals/${id}/activities`,
    share: (token: string) => `/api/v1/proposals/share/${token}`,
    sendForSigning: (id: string) => `/api/v1/proposals/${id}/send-for-signing`,
    resend: (id: string) => `/api/v1/proposals/${id}/resend`,
    signInternal: (id: string) => `/api/v1/proposals/${id}/sign-internal`,
    signatureStatus: (id: string) => `/api/v1/proposals/${id}/signature-status`,
    session: (token: string) => `/api/v1/proposals/share/${token}/session`,
    consent: (token: string) => `/api/v1/proposals/share/${token}/consent`,
    complianceSign: (token: string) => `/api/v1/proposals/share/${token}/compliance-sign`,
    complianceSignInternal: (id: string) => `/api/v1/proposals/${id}/compliance-sign-internal`,
    auditEvents: (id: string) => `/api/v1/proposals/${id}/audit-events`,
    evidencePackages: (id: string) => `/api/v1/proposals/${id}/evidence-packages`,
    verifySignature: `/api/v1/proposals/verify`,
  },
  legal: {
    list: "/api/v1/legal",
    stats: "/api/v1/legal/stats",
    create: "/api/v1/legal",
    detail: (id: string) => `/api/v1/legal/${id}`,
    update: (id: string) => `/api/v1/legal/${id}`,
    delete: (id: string) => `/api/v1/legal/${id}`,
    uploadVersion: (id: string) => `/api/v1/legal/${id}/versions`,
    versions: (id: string) => `/api/v1/legal/${id}/versions`,
    activities: (id: string) => `/api/v1/legal/${id}/activities`,
  },
  finance: {
    stats: "/api/v1/finance/stats",
    overdue: "/api/v1/finance/overdue",
    records: "/api/v1/finance/records",
    recordDetail: (id: string) => `/api/v1/finance/records/${id}`,
    invoices: "/api/v1/finance/invoices",
    invoiceDetail: (id: string) => `/api/v1/finance/invoices/${id}`,
    payments: "/api/v1/finance/payments",
    paymentDetail: (id: string) => `/api/v1/finance/payments/${id}`,
    clientSummary: (clientId: string) => `/api/v1/finance/clients/${clientId}/summary`,
    activities: "/api/v1/finance/activities",
  },
  knowledge: {
    stats: "/api/v1/knowledge/stats",
    list: "/api/v1/knowledge",
    create: "/api/v1/knowledge",
    detail: (id: string) => `/api/v1/knowledge/${id}`,
    update: (id: string) => `/api/v1/knowledge/${id}`,
    delete: (id: string) => `/api/v1/knowledge/${id}`,
    restore: (id: string) => `/api/v1/knowledge/${id}/restore`,
    favorite: (id: string) => `/api/v1/knowledge/${id}/favorite`,
    favorites: "/api/v1/knowledge/favorites",
    versions: (id: string) => `/api/v1/knowledge/${id}/versions`,
    restoreVersion: (id: string, v: number) => `/api/v1/knowledge/${id}/versions/${v}/restore`,
    activities: (id: string) => `/api/v1/knowledge/${id}/activities`,
    related: (id: string) => `/api/v1/knowledge/${id}/related`,
  },

} as const;
